name: Test and build artifact with Maven

on:
  push:
    paths-ignore:
    - 'README.md'

jobs:
  test-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        architecture: x64
        cache: maven
    - name: Build and test application
      run: mvn -B package -f pom.xml

  publish-job:
    runs-on: windows-latest
    needs: test-build
    steps:
    - uses: actions/checkout@v4
    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        architecture: x64
        cache: maven
    - name: Verify application
      run: mvn -B verify -DskipTests -f pom.xml
    - name: Create target directories
      run: mkdir staging && mkdir staging\lib
    - name: Copy file and dependencies
      run: copy target\*.jar staging && copy target\lib\* staging\lib && copy target\classes\[TF1D].csv staging
    - uses: actions/upload-artifact@v4
      with:
        name: JavaMarketTraderPackage
        path: staging
